import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FeaturedProducts from "@/components/FeaturedProducts";
import getAllProducts from "@/services/productService";
import SearchBar from "@/components/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <nav>
          <a href="/">Home</a>
          <a href="/blog/first-blog">First Blog</a>
          <a href="/about">About</a>
        </nav>
        <SearchBar />
        
        {children}
        <footer>Copyright</footer>
      </body>
    </html>
  );
}
